{% set name = "mlflow" %}
{% set version = "3.7.0" %}

package:
  name: mlflow-split
  version: {{ version }}

source:
  url: https://github.com/mlflow/mlflow/archive/refs/tags/v{{ version }}.zip
  sha256: fd7700cf535538de5135db02ad51f3b272c1a216cc00a9d1f0c5d1be738ab63d
  patches:
    - 0001-Build-leaner-source-maps.patch

build:
  number: 0
  noarch: python

outputs:
  - name: mlflow-skinny
    script: build-mlflow.sh  # [unix]
    script: build-mlflow.bat  # [win]
    version: {{ version }}
    build:
      noarch: python
      entry_points:
        - mlflow=mlflow.cli:cli
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - cachetools <7,>=5.0.0
        - click <9,>=7.0
        - cloudpickle <4
        - databricks-sdk <1,>=0.20.0
        - fastapi <1
        - gitpython <4,>=3.1.9
        - importlib-metadata <9,>=3.7.0,!=4.7.0
        - opentelemetry-api <3,>=1.9.0
        - opentelemetry-proto <3,>=1.9.0
        - opentelemetry-sdk <3,>=1.9.0
        - packaging <26
        - protobuf <7,>=3.12.0
        - pydantic <3,>=1.10.8
        - python-dotenv <2,>=0.19.0
        - pyyaml <7,>=5.1
        - requests <3,>=2.17.3
        - sqlparse <1,>=0.4.0
        - typing-extensions <5,>=4.0.0
        - uvicorn <1
        - __unix  # [unix]
        - __win  # [win]
    test:
      imports:
        - mlflow
        - mlflow.entities
        - mlflow.projects
        - mlflow.protos
        - mlflow.rfunc
        - mlflow.store
        - mlflow.tracking
        - mlflow.utils
      commands:
        - mlflow --help
        - pip list | grep "mlflow-skinny \+${PKG_VERSION}"  # [unix]
        - pip check
      requires:
        - pip
        - python {{ python_min }}
  - name: mlflow
    script: build-mlflow.sh  # [unix]
    script: build-mlflow.bat  # [win]
    version: {{ version }}
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - {{ pin_subpackage('mlflow-ui', exact=True) }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mlflow-ui', exact=True) }}
        - alembic <2,!=1.10
        - cachetools <7,>=5.0.0
        - click <9,>=7.0
        - cloudpickle <4
        - cryptography <47,>=43.0.0
        - databricks-sdk <1,>=0.20.0
        - docker-py >=4.0.0,<8
        - fastapi <1
        - flask <4
        - flask-cors <7
        - gitpython <4,>=3.1.9
        - graphene <4
        - gunicorn <24  # [not win]
        - huey <3,>=2.5.0
        - importlib-metadata <9,>=3.7.0,!=4.7.0
        - matplotlib-base <4
        - numpy <3
        - opentelemetry-api <3,>=1.9.0
        - opentelemetry-proto <3,>=1.9.0
        - opentelemetry-sdk <3,>=1.9.0
        - packaging <26
        - pandas <3
        - prometheus_flask_exporter <1
        - protobuf <7,>=3.12.0
        - pyarrow <22,>=4.0.0
        - pydantic <3,>=1.10.8
        - python-dotenv <2,>=0.19.0
        - pyyaml <7,>=5.1
        - requests <3,>=2.17.3
        - scikit-learn <2
        - scipy <2
        - sqlalchemy >=1.4.0,<3
        - sqlparse <1,>=0.4.0
        - typing-extensions <5,>=4.0.0
        - uvicorn <1
        - waitress <4  # [win]
        - __unix  # [unix]
        - __win  # [win]
    test:
      imports:
        - mlflow
        - mlflow.entities
        - mlflow.models
        - mlflow.projects
        - mlflow.protos
        - mlflow.pyfunc
        - mlflow.pytorch
        - mlflow.rfunc
        - mlflow.sagemaker
        - mlflow.server
        - mlflow.server.prometheus_exporter
        - mlflow.store
        - mlflow.tracking
        - mlflow.utils
      commands:
        - mlflow --help
        # This should not be packaged
        - test ! -f $SP_DIR/pylint_plugins  # [unix]
        - pip check
        - pip list | grep "mlflow \+${PKG_VERSION}"  # [unix]
        - set  # [win]
      requires:
        - pip
        - python {{ python_min }}

  - name: mlflow-ui-dbg
    version: {{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        # Prevent solver errors with pandas
        - setuptools
        - {{ pin_subpackage('mlflow', exact=True) }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mlflow', exact=True) }}
        - __unix  # [unix]
        - __win  # [win]
    script: build-mlflow.bat  # [win]
    script: build-mlflow.sh  # [unix]
    test:
      requires:
        - python {{ python_min }}
      commands:
        - exit 0

  - name: mlflow-skinny-gateway
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        # Prevent solver errors with pandas
        - setuptools
        - {{ pin_subpackage('mlflow-skinny', exact=True) }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mlflow-skinny', exact=True) }}
        - aiohttp <4
        - boto3 <2,>=1.28.56
        - fastapi <1
        - slowapi <1,>=0.1.9
        - tiktoken <1
        - uvicorn <1
        - watchfiles <2
        - __unix  # [unix]
        - __win  # [win]
    test:
      requires:
        - python {{ python_min }}
      imports:
        - mlflow.gateway

  - name: mlflow-gateway
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        # Prevent solver errors with pandas
        - setuptools
        - {{ pin_subpackage('mlflow', exact=True) }}
        - {{ pin_subpackage('mlflow-skinny-gateway', exact=True) }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mlflow', exact=True) }}
        - {{ pin_subpackage('mlflow-skinny-gateway', exact=True) }}
        - __unix  # [unix]
        - __win  # [win]
    test:
      requires:
        - python {{ python_min }}
      imports:
        - mlflow.gateway


  - name: mlflow-ui
    version: {{ version }}
    build:
      noarch: python
    requirements:
      build:
        - nodejs 20.*
        - yarn
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - {{ pin_subpackage('mlflow-skinny', exact=True) }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mlflow-skinny', exact=True) }}
        - flask <4
        - gunicorn <24  # [not win]
        - waitress <4  # [win]
        - querystring_parser <2
        - __unix  # [unix]
        - __win  # [win]
    script: build-mlflow.bat  # [win]
    script: build-mlflow.sh  # [unix]
    test:
      requires:
        - python {{ python_min }}
      commands:
        - mlflow --help
        - test -f $SP_DIR/mlflow/server/js/build/index.html               # [unix]
        - if not exist %SP_DIR%\mlflow\server\js\build\index.html exit 1  # [win]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  feedstock-name: mlflow
  recipe-maintainers:
    - TomeHirata
    - daniellok-db
    - B-Step62
    - serena-ruan
    - BenWilson2
    - WeichenXu123
    - harupy
    - dbczumar
    - jaroslawk
    - xhochy
    - janjagusch
