{% set name = "mlflow" %}
{% set version = "1.23.0" %}
{% if mlflow_variant == "skinny" %}
{% set mlflow_suffix = "-skinny" %}
{% set mlflow_other = "" %}
{% else %}
{% set mlflow_suffix = "" %}
{% set mlflow_other = "-skinny" %}
{% endif %}

package:
  name: mlflow-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66a1959a5d09bd5f2bd46ba53233c964973c2ef7e16bb4498f1bcc61bb3403c5

build:
  number: 0

outputs:
  - name: mlflow{{ mlflow_suffix }}
    script: build-mlflow.sh  # [unix]
    script: build-mlflow.bat  # [win]
    version: {{ version }}
    build:
      entry_points:
        - mlflow=mlflow.cli:cli
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - alembic <=1.4.1  # [mlflow_variant != "skinny"]
        - click >=7.0
        - cloudpickle
        - databricks-cli >=0.8.7
        - docker-py >=4.0.0  # [mlflow_variant != "skinny"]
        - entrypoints
        - flask  # [mlflow_variant != "skinny"]
        - gitpython >=2.1.0
        - gunicorn  # [not win and mlflow_variant != "skinny"]
        - numpy  # [mlflow_variant != "skinny"]
        - pandas  # [mlflow_variant != "skinny"]
        - prometheus_flask_exporter  # [mlflow_variant != "skinny"]
        - packaging
        - protobuf >=3.7.0
        - python
        - pytz
        - pyyaml >=5.1
        - querystring_parser  # [mlflow_variant != "skinny"]
        - requests >=2.17.3
        - sqlalchemy  # [mlflow_variant != "skinny"]
        - sqlparse >=0.3.1  # [mlflow_variant != "skinny"]
        - waitress  # [win and mlflow_variant != "skinny"]
        - importlib-metadata
        - openssl
      run_constrained:
        - mlflow{{ mlflow_other }} <0a0
    test:
      imports:
        - mlflow
        - mlflow.azureml  # [mlflow_variant != "skinny"]
        - mlflow.entities
        - mlflow.models  # [mlflow_variant != "skinny"]
        - mlflow.projects
        - mlflow.protos
        - mlflow.pyfunc  # [mlflow_variant != "skinny"]
        - mlflow.pytorch  # [mlflow_variant != "skinny"]
        - mlflow.rfunc
        - mlflow.sagemaker  # [mlflow_variant != "skinny"]
        - mlflow.server  # [mlflow_variant != "skinny"]
        - mlflow.server.prometheus_exporter  # [mlflow_variant != "skinny"]
        - mlflow.store
        - mlflow.tracking
        - mlflow.utils
      commands:
        - mlflow --help
        - pip check
      requires:
        - pip

  - name: mlflow-ui-dbg{{ mlflow_suffix }}
    build:
      skip: true  # [mlflow_variant == "skinny"]
    version: {{ version }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - openssl
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
      run:
        - python
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
    script: build-mlflow.bat  # [win]
    script: build-mlflow.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  feedstock-name: mlflow
  recipe-maintainers:
    - aarondav
    - ahirreddy
    - andrewmchen
    - aveshcsingh
    - dbczumar
    - jaroslawk
    - mateiz
    - mparkhe
    - pogil
    - smurching
    - sueann
    - tomasatdatabricks
    - xhochy
    - zangr
    - janjagusch
