{% set name = "mlflow" %}
{% set version = "1.27.0" %}
{% if mlflow_variant == "skinny" %}
{% set mlflow_suffix = "-skinny" %}
{% set mlflow_other = "" %}
{% else %}
{% set mlflow_suffix = "" %}
{% set mlflow_other = "-skinny" %}
{% endif %}

package:
  name: mlflow-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a1e34d6be266725e41d4547572a8425d86d6623e1c8888cf3f22b90019be0aa

build:
  number: 0

outputs:
  - name: mlflow{{ mlflow_suffix }}
    script: build-mlflow.sh  # [unix]
    script: build-mlflow.bat  # [win]
    version: {{ version }}
    build:
      entry_points:
        - mlflow=mlflow.cli:cli
        - mlp=mlflow.pipelines.cli:commands
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - alembic  # [mlflow_variant != "skinny"]
        - click >=7.0
        - cloudpickle
        - databricks-cli >=0.8.7
        - docker-py >=4.0.0  # [mlflow_variant != "skinny"]
        - entrypoints
        - flask  # [mlflow_variant != "skinny"]
        - gitpython >=2.1.0
        - gunicorn  # [not win and mlflow_variant != "skinny"]
        - numpy  # [mlflow_variant != "skinny"]
        - pandas  # [mlflow_variant != "skinny"]
        - prometheus_flask_exporter  # [mlflow_variant != "skinny"]
        - packaging
        - protobuf >=3.12.0
        - python
        - pytz
        - pyyaml >=5.1
        - querystring_parser  # [mlflow_variant != "skinny"]
        - requests >=2.17.3
        - scipy  # [mlflow_variant != "skinny"]
        - sqlalchemy >=1.4.0  # [mlflow_variant != "skinny"]
        - sqlparse >=0.3.1  # [mlflow_variant != "skinny"]
        - waitress  # [win and mlflow_variant != "skinny"]
        - importlib-metadata
        - openssl
        # MLflow Pipelines dependencies
        - scikit-learn >=1.0.*  # [mlflow_variant != "skinny"]
        - pyarrow >=7.0.*  # [mlflow_variant != "skinny"]
        - shap >=0.40.*  # [mlflow_variant != "skinny"]
        # pandas-profiling version is not restricted to prevent the following jobs from failing:
        # - linux linux_ppc64le_mlflow_variantdefaultpython3.10.____cpython
        # - linux linux_ppc64le_mlflow_variantdefaultpython3.9.____cpython
        - pandas-profiling  # [mlflow_variant != "skinny"]
        - ipython >=7.0.*  # [mlflow_variant != "skinny"]
        - markdown >=3.3.*  # [mlflow_variant != "skinny"]
        - Jinja2 >=3.0.*  # [mlflow_variant != "skinny"]
      run_constrained:
        - mlflow{{ mlflow_other }} <0a0
    test:
      imports:
        - mlflow
        - mlflow.azureml  # [mlflow_variant != "skinny"]
        - mlflow.entities
        - mlflow.models  # [mlflow_variant != "skinny"]
        - mlflow.projects
        - mlflow.protos
        - mlflow.pyfunc  # [mlflow_variant != "skinny"]
        - mlflow.pytorch  # [mlflow_variant != "skinny"]
        - mlflow.rfunc
        - mlflow.sagemaker  # [mlflow_variant != "skinny"]
        - mlflow.server  # [mlflow_variant != "skinny"]
        - mlflow.server.prometheus_exporter  # [mlflow_variant != "skinny"]
        - mlflow.store
        - mlflow.tracking
        - mlflow.utils
      commands:
        - mlflow --help
        - mlp --help
        - pip check
      requires:
        - pip

  - name: mlflow-ui-dbg{{ mlflow_suffix }}
    build:
      skip: true  # [mlflow_variant == "skinny"]
    version: {{ version }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        # Prevent solver errors with pandas
        - setuptools <60
        - openssl
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
      run:
        - python
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
    script: build-mlflow.bat  # [win]
    script: build-mlflow.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  feedstock-name: mlflow
  recipe-maintainers:
    - harupy
    - aarondav
    - ahirreddy
    - andrewmchen
    - aveshcsingh
    - dbczumar
    - jaroslawk
    - mateiz
    - mparkhe
    - pogil
    - smurching
    - sueann
    - tomasatdatabricks
    - xhochy
    - zangr
    - janjagusch
