{% set name = "mlflow" %}
{% set version = "2.0.0" %}
{% if mlflow_variant == "skinny" %}
{% set mlflow_suffix = "-skinny" %}
{% set mlflow_other = "" %}
{% else %}
{% set mlflow_suffix = "" %}
{% set mlflow_other = "-skinny" %}
{% endif %}

package:
  name: mlflow-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd191cae66493edfd28ebb65223aad89231e8fe6a9b2b399305a97aa9056ec87

build:
  number: 0

outputs:
  - name: mlflow{{ mlflow_suffix }}
    script: build-mlflow.sh  # [unix]
    script: build-mlflow.bat  # [win]
    version: {{ version }}
    build:
      entry_points:
        - mlflow=mlflow.cli:cli
        - mlp=mlflow.pipelines.cli:commands
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - alembic <2  # [mlflow_variant != "skinny"]
        - click >=7.0,<9
        - cloudpickle <3
        - databricks-cli >=0.8.7,<1
        - docker-py >=4.0.0,<7  # [mlflow_variant != "skinny"]
        - entrypoints <1
        - flask <3  # [mlflow_variant != "skinny"]
        - gitpython >=2.1.0,<4
        - gunicorn <21  # [not win and mlflow_variant != "skinny"]
        - numpy <2  # [mlflow_variant != "skinny"]
        - pandas <2  # [mlflow_variant != "skinny"]
        - prometheus_flask_exporter <1  # [mlflow_variant != "skinny"]
        - packaging <22
        - protobuf >=3.12.0,<5
        - python
        - pytz <2023
        - pyyaml >=5.1,<7
        - querystring_parser <2  # [mlflow_variant != "skinny"]
        - requests >=2.17.3,<3
        - scipy <2  # [mlflow_variant != "skinny"]
        - sqlalchemy >=1.4.0,<2  # [mlflow_variant != "skinny"]
        - sqlparse >=0.4.0,<1
        - waitress <3  # [win and mlflow_variant != "skinny"]
        - importlib-metadata <6,>=3.7.0,!=4.7.0
        - openssl
      run_constrained:
        - mlflow{{ mlflow_other }} <0a0
    test:
      imports:
        - mlflow
        - mlflow.azureml  # [mlflow_variant != "skinny"]
        - mlflow.entities
        - mlflow.models  # [mlflow_variant != "skinny"]
        - mlflow.projects
        - mlflow.protos
        - mlflow.pyfunc  # [mlflow_variant != "skinny"]
        - mlflow.pytorch  # [mlflow_variant != "skinny"]
        - mlflow.rfunc
        - mlflow.sagemaker  # [mlflow_variant != "skinny"]
        - mlflow.server  # [mlflow_variant != "skinny"]
        - mlflow.server.prometheus_exporter  # [mlflow_variant != "skinny"]
        - mlflow.store
        - mlflow.tracking
        - mlflow.utils
      commands:
        - mlflow --help
        - mlp --help  # [mlflow_variant != "skinny"]
        - pip check
        - set  # [win]
      requires:
        - pip

  - name: mlflow-ui-dbg{{ mlflow_suffix }}
    build:
      skip: true  # [mlflow_variant == "skinny"]
    version: {{ version }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        # Prevent solver errors with pandas
        - setuptools <60
        - openssl
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
      run:
        - python
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
    script: build-mlflow.bat  # [win]
    script: build-mlflow.sh  # [unix]

  - name: mlflow-pipelines{{ mlflow_suffix }}
    build:
      skip: true  # [mlflow_variant == "skinny"]
    version: {{ version }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        # Prevent solver errors with pandas
        - setuptools <60
        - openssl
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
      run:
        - python
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
        - scikit-learn >=1.0
        - pyarrow >=7.0
        - shap >=0.40
        - pandas-profiling >=3.1
        - ipython>=7.0
        - markdown >=3.3
        - jinja2 >=3.0
    script: noop.bat  # [win]
    script: noop.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  feedstock-name: mlflow
  recipe-maintainers:
    - WeichenXu123
    - harupy
    - aarondav
    - ahirreddy
    - andrewmchen
    - aveshcsingh
    - dbczumar
    - jaroslawk
    - mateiz
    - mparkhe
    - pogil
    - smurching
    - sueann
    - tomasatdatabricks
    - xhochy
    - zangr
    - janjagusch
