{% set name = "mlflow" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "77f44dc2dc79f843cd7a2d2a6371066363bef248d5739e520243db0aacb1c037"

build:
  number: 0
  noarch: python
  entry_points:
    - mlflow=mlflow.cli:cli

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - alembic
    - click >=7.0
    - cloudpickle
    - databricks-cli >=0.8.7
    - docker-py >=3.6.0
    - entrypoints
    - flask
    - gitpython >=2.1.0
    - gorilla
    - gunicorn
    - numpy
    - pandas
    - pip
    - protobuf >=3.6.0
    - python >=3.6.0
    - python-dateutil
    - pyyaml
    - querystring_parser
    - requests >=2.17.3
    - simplejson
    - six >=1.10.0
    - sqlalchemy
    - sqlparse

test:
  imports:
    - mlflow
    - mlflow.azureml
    - mlflow.entities
    - mlflow.models
    - mlflow.projects
    - mlflow.protos
    - mlflow.pyfunc
    - mlflow.pytorch
    - mlflow.rfunc
    - mlflow.sagemaker
    - mlflow.server
    - mlflow.store
    - mlflow.tracking
    - mlflow.utils
  commands:
    - mlflow --help

outputs:
  - name: mlflow
    version: {{ version }}
    files:
      - "lib/python{{ PY_VER }}/site-packages/mlflow"
  - name: mlflow-ui-dbg
    version: {{ version }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('mlflow', exact=True) }}
    script: install_maps.sh


about:
  home: https://mlflow.org/
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  recipe-maintainers:
    - andrewmchen
    - jaroslawk
