{% set name = "mlflow" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11fe050373f3dbd422aa476c42cb0ed15467268bc1ad07e221e550bc54f94b75

build:
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - alembic
    - azure-storage-blob >=12.0
    - click >=7.0
    - cloudpickle
    - databricks-cli >=0.8.7
    - docker-py >=4.0.0
    - entrypoints
    - flask
    - gitpython >=2.1.0
    - gorilla
    - gunicorn  # [not win]
    - numpy
    - pandas
    - prometheus_flask_exporter
    - protobuf >=3.6.0
    - python
    - python-dateutil
    - pyyaml
    - querystring_parser
    - requests >=2.17.3
    - six >=1.10.0
    - sqlalchemy <=1.3.13
    - sqlparse
    - waitress  # [win]

test:
  imports:
    - mlflow
    - mlflow.azureml
    - mlflow.entities
    - mlflow.models
    - mlflow.projects
    - mlflow.protos
    - mlflow.pyfunc
    - mlflow.pytorch
    - mlflow.rfunc
    - mlflow.sagemaker
    - mlflow.server
    - mlflow.server.prometheus_exporter
    - mlflow.store
    - mlflow.tracking
    - mlflow.utils
  commands:
    - mlflow --help  # [not win]
    - pip check  # [not win]
  requires:
    - pip

outputs:
  - name: mlflow
    version: {{ version }}
    files:
      - bin/mlflow*    # [unix]
      - lib/python{{ PY_VER }}/site-packages/mlflow    # [unix]
      - lib/python{{ PY_VER }}/site-packages/mlflow-*    # [unix]
      - Scripts\mlflow*     # [win]
      - Lib\site-packages\mlflow      # [win]
      - Lib\site-packages\mlflow-*      # [win]
  - name: mlflow-ui-dbg
    version: {{ version }}
    requirements:
      run:
        - python
        - {{ pin_subpackage('mlflow', exact=True) }}
    script: install_maps.bat  # [win]
    script: install_maps.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  recipe-maintainers:
    - aarondav
    - ahirreddy
    - andrewmchen
    - aveshcsingh
    - dbczumar
    - jaroslawk
    - mateiz
    - mparkhe
    - pogil
    - smurching
    - sueann
    - tomasatdatabricks
    - xhochy
    - zangr
